const fs = require("fs");
const path = require("path");

const ENV_PATH = path.join(__dirname, ".env");
const OUTPUT_PATH = path.join(__dirname, "config.js");

// Only expose client-safe keys to the browser.
const PUBLIC_KEYS = [
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "STRIPE_CHECKOUT_URL",
];

const readEnvFile = () => {
  if (!fs.existsSync(ENV_PATH)) {
    console.error("Missing .env. Copy .env.example and fill values.");
    process.exit(1);
  }

  const raw = fs.readFileSync(ENV_PATH, "utf8");
  const env = {};

  raw.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      return;
    }

    const index = trimmed.indexOf("=");
    if (index === -1) {
      return;
    }

    const key = trimmed.slice(0, index).trim();
    let value = trimmed.slice(index + 1).trim();

    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  });

  return env;
};

const env = readEnvFile();
const publicConfig = {};

PUBLIC_KEYS.forEach((key) => {
  if (env[key]) {
    publicConfig[key] = env[key];
  }
});

const output = `// Auto-generated by build-config.js. Do not edit by hand.\nwindow.RUNTIME_CONFIG = ${JSON.stringify(
  publicConfig,
  null,
  2
)};\n`;

fs.writeFileSync(OUTPUT_PATH, output, "utf8");
console.log(`Generated config.js with ${Object.keys(publicConfig).length} keys.`);
