// Auto-generated by build-config.js. Do not edit by hand.
window.RUNTIME_CONFIG = {
  "SUPABASE_URL": "https://ezwzjfhbeuwnxnjjhrxq.supabase.co",
  "SUPABASE_ANON_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6d3pqZmhiZXV3bnhuampocnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNzY3MzksImV4cCI6MjA4Njg1MjczOX0.wFJaFknBGc6DTUwG8ANWeiiNg4pBGdeHcvi1kOU1AcI",
  "STRIPE_CHECKOUT_URL": "https://buy.stripe.com/your-checkout-link"
};
