// Auto-generated by build-config.js. Do not edit by hand.
window.RUNTIME_CONFIG = {
  "SUPABASE_URL": "https://your-project.supabase.co",
  "SUPABASE_ANON_KEY": "your-supabase-anon-key",
  "STRIPE_CHECKOUT_URL": "https://buy.stripe.com/your-checkout-link"
};
